### PR TITLE
remove unused instance initializers

### LINKED ISSUE #20: Instance Initializer unused?
👋 

I was wondering what the use case for [this](https://github.com/sreedhar7/ember-app-scheduler/blob/master/addon/instance-initializers/init-app-scheduler.js) instance-initializer was?  Is it possible to remove?

### PR DESCRIPTION
**Pull request by snewcomer**
Close #20

### CODE REVIEW

**Comment by scalvert** [comment]
It's not actually unused. The initializer's job is to register stuff for DI. The instance initializer is to init it via lookup. The reason we have both is to avoid a race condition between the initializer and the instance initializer.

**Comment by snewcomer** [comment]
@scalvert Ah gotcha!  So I might be missing something, but the first thing I tested was removing the instance initializers to see if my app would still work and didn't have any problems.  Second, I thought the two phase initialization processes prevented race conditions.  Also, I isn't the consumer injecting the service, in say a controller or router in the consuming application init-ing an instance?

Is this perhaps important for fastboot?  Lmk what you think.  I would love to learn something I didn't know!

**Comment by rwjblue** [comment]
> Also, isn't the consumer injecting the service, in say a controller or router in the consuming application stamping out an instance?

Doing `foo: inject.service()` does not cause the `foo` service to be instantiated when the object itself is created. Only calling `this.get(‘foo’)` would cause that.

**Comment by snewcomer** [comment]
@rwjblue Oh right.  Yeah I didn't think that one through all the way 😅.  But the user (or another addon), at some point will get an instance if they ask for the service with `get` and call it's methods, right?  So a bit confused on the instance-initializer use case.

**Comment by scalvert** [comment]
This is being addressed in #26 as part of a larger revamp. I'm going to close this in favor of that, if that's ok.

**Pull request closed without merging**
