### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by rondale-sc**

### CODE REVIEW

**Comment by sreedhar7** [comment]
It looks like the repository field is supposed to have the repo URL which has the source code for the project. https://docs.npmjs.com/files/package.json#repository

Can you explain in detail why you have raised this pull request?

**Comment by rondale-sc** [comment]
@sreedhar7 You are quite that I've entered this incorrectly (I'll fix that).  The reason I wanted to do this is beause when I search for ember-app-scheduler npm regitry pops up as the first hit, but I usually want to go to the github page.  Without a properly filled out repository field the link from the npm registry to here doesn't exist.

**Comment by rondale-sc** [comment]
@sreedhar7 It's been updated.  Sorry about the confusion!  :( 

Awesome little lib btw. :)

**Comment by sreedhar7** [comment]
Thanks for the quick response and fixing this.

**Comment by sreedhar7** [comment]
Thanks for making the change @rondale-sc . FYI, I noticed a parsing issue in package.json. Please run tests in future before submitting the PR.

**Comment by rondale-sc** [comment]
@sreedhar7 Will do!  Everytime I try to make simple edits with the GitHub in browser editor I always run into things like this.

**Pull request merged**
